### ISSUE TITLE
Merge the clojure cheatsheet in helm-cider

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/helm-cider#9]
https://github.com/clojure-emacs/clojure-cheatsheet is basically abandonware at this point and it just displays the Clojure cheatsheet using Helm. Seems reasonable to move the core logic to CIDER and expose it via two consecutive `completing-read` calls (or something like `browse-ns` type of interface) in CIDER itself and move the helm-related stuff here.

**Comment by xiongtx** [comment]
I'm not a fan of the Helm interface there at all--how is the user supposed to scan and navigate to the different sections, which is the purpose of a cheatsheet?

![image](https://user-images.githubusercontent.com/1624090/35468125-c3ab6608-02cc-11e8-83b9-2feb9458293a.png)

If this does get incorporated in `helm-cider`, there'd need to be some interface that allows the user to view selection the heading first (similar to `cider-browse-ns`).

**Comment by bbatsov** [comment]
That's fine by me. Seems we're in agreement about the what the format of the data should be and that it's fine for it to live in CIDER.

**Comment by xiongtx** [comment]
It turns out that `helm-multi-match` is used to match the query against headings as well, which is pretty clever. I've partially implemented a solution that narrows by heading levels (in the `cheatsheet-narrow` branch), but the the UX isn't very good. In particular, it'd be a pain to navigate down and up heading levels.

We'll just use clean up @krisajenkins's code a bit for now. If there's a better UX solution down the road we can implement that.
